### PR TITLE
SF-6393 Millisecond Ordering

### PR DESCRIPTION
**Pull request by danatcofo**

### CODE REVIEW

**Comment by sporty81** [comment]
I thought we handled this because the log msgid was a sequentialguid and you could sort by it?

**Comment by danatcofo** [comment]
@sporty81 this is for ES performance.  Sorting on the id performs terribly. sorting on an integer like this performs awesomely.  We have platform code in place to convert the uid order into an integer like this does here within a single batch. However doing it here ensures that the order would be good even across multiple batches.

**Comment by sporty81** [comment]
Can we do the sort on the guid in our API (one time) and add the order field there so we don't have to mess with all of our libraries?

**Comment by danatcofo** [comment]
We are going to do it in the workers, however we wanted to provided an option for clients on the lib side should they notice any inconsistencies (however unlikely).  This update would be entirely optional and not required to support our performance tunings.

**Pull request merged**
