### PR TITLE
NLog.Targets.Stackify - Added logAllProperties for structured logging

### LINKED ISSUE #56: NLog target does not capture Properties
NLog has [Event Properties](https://github.com/nlog/nlog/wiki/EventProperties-Layout-Renderer) which is used for logging custom values. 

```c#
LogEventInfo theEvent = new LogEventInfo(LogLevel.Debug, "", "Pass my custom value");
theEvent.Properties.Add("MyValue", "My custom string");
theEvent.Properties.Add("MyDateTimeValue", new DateTime(2015, 08, 30, 11, 26, 50));
logger.Log(theEvent);
```

Currently the NLog target does not capture these values and it would be very nice if it could.

a naive fix would be adding something like below 

```csharp
if (loggingEvent.Properties.Any())
{
    // capture properties of log event
   loggingEvent
         .Properties
         .ToList()
         .ForEach(prop => diags.Add(prop.Key.ToString(), prop.Value));
 }
```
after 
https://github.com/stackify/stackify-api-dotnet/blob/ed40f4c7e09418f135ef3bea01c07b27cdeec055/Src/NLog.Targets.Stackify/StackifyTarget.cs#L296-L301

### PR DESCRIPTION
**Pull request by snakefoot**
Resolve #56 

Also changed dependencies to NLog 4.5, as it will be the next official release.

### CODE REVIEW

**Comment by snakefoot** [comment]
@strvmarv Build is failing with "Specify which project or solution file to use because the folder contains more than one project or solution file."

Is some configuration missing?

https://help.appveyor.com/discussions/problems/6037-specify-which-project-or-solution-file-to-use-because-the-folder-contains-more-than-one-project-or-solution-file

**Comment by strvmarv** [comment]
@snakefoot 

Sorry about that...we have two branches running simultaneously at the moment (master & develop) and currently only develop builds via appveyor...

**Comment by snakefoot** [comment]
@strvmarv Should I target the develop-branch instead?

**Comment by strvmarv** [comment]
@snakefoot No, you targeted the correct branch in this case 👍

**Comment by snakefoot** [comment]
I'm curious if the `ToLower` operation can be skipped for the properties-keys, since `ToLower` will always allocate a new string (NDC + MDC is using ToLower)

**Comment by snakefoot** [comment]
@strvmarv Added an extra modification by making it possible to disable the scanning for last debug parameter.

**Comment by snakefoot** [comment]
@strvmarv Recognized that LogEvent-Properties/Parameters/Args are different than LogEvent-Context. Have now changed so LogEvent-Properties are prioritized if they are available, and not mixed together with LogEvent-Context-Properties.

Also modified helper method SerializeDebugData to maintain the same behavior on NetCore for generic types.

**Comment by strvmarv** [comment]
Packages have been updated, but are currently unlisted...you can find them here...

https://www.nuget.org/packages/NLog.Targets.Stackify/2.0.2
https://www.nuget.org/packages/StackifyLib/2.0.3

**Pull request merged**
