### PR TITLE
Updated README.md about structured logging in NLog 4.5

### PR DESCRIPTION
**Pull request by snakefoot**
Example:

https://github.com/snakefoot/stackify-api-dotnet/blob/master/README.md#nlog

See also: https://github.com/NLog/NLog/wiki/How-to-use-structured-logging

### CODE REVIEW

**Comment by snakefoot** [comment]
@mattjbrooksii Time for review?

**Comment by snakefoot** [comment]
@kbond-stackify Can this also be merged?

**Review by kbond-stackify — APPROVED** [review]

**Comment by snakefoot** [comment]
Thank you very much.

**Comment by snakefoot** [comment]
@homiedopie & @kbond-stackify Should `develop`-branch not be merged into `master` with the relase of [v2.1.10](https://www.nuget.org/packages/StackifyLib/) ?

**Pull request merged**
