### PR TITLE
Add user agent to web request details

### PR DESCRIPTION
**Pull request by evest**
This allows us to quickly identify if specific browsers are the cause of errors or problems (especially useful to detect crawlers attempting paths or queries they clearly shouldn't).

I've observed really strange and unexpected errors caused by crawlers revisiting old urls or selectively picking query string parameters. Being able to inspect the user agent will help us identify these.

### CODE REVIEW

**Comment by danatcofo** [comment]
@sporty81, @eric-martin this would require a platform change as well to pass through the user agent.  Not a huge deal.  Do we have any security concerns about including it or not?

**Comment by eric-martin** [comment]
No concerns. Approved.

**Comment by danatcofo** [comment]
Added SF-6436 to Platform Jira Queue, tentatively scheduled for 2017.04 release, will update here when available.

**Comment by evest** [comment]
👍 Thanks!

**Comment by danatcofo** [comment]
SF-6436 is coded and in queue for 2017.04 release, will update here when release has occurred.

**Comment by danatcofo** [comment]
@evest The platform updates to support this are now released.  Enjoy

**Pull request merged**
